name: FunCooldowns
version: '1.0'
main: me.jetby.cmdTimer.Main
api-version: '1.16'
authors: [ TreexStudio ]
website: https://dsc.gg/treexstudio
commands:
  cmdtimer-reload:
    aliases:
      - funcooldowns
      - fc
  cancelteleport: {}